language: python
python:
- 3.6.4
env:
- DJANGO=2.0.2
install:
- pip install -r requirements.txt
before_script:
- python3 manage.py makemigrations
- python3 manage.py migrate
script:
- flake8
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: "X0rq4g3ypWMurUO4I7qonAWQLxypweu/cTFtRC/6+Iv1kPt9QJ4iJmkN6VTERrSym6NrYReHlJVMhSeLiE/UpwbmkNNiXiTPr4vrRbxhZotxruBcBIUbNsw4vFg3/Y4uEbPm8msiyYqFwh4g5Vgu/01wsasisFRvovUKCFaShKAbp4tBBYfuz+mKISZdCRm/D/Gn0WFxWXcFYaH/F7GotrzIRR3gVmGjsFVgFQ/HHnyBvyW5ox2Qqa+FIXFXpg/TxXyf6sjid3e1RNtmACm36Xa6i6EK0tuG2SK3HtFc8MDLg6MzUI9adKyP+/LsqtP3mbbmvUbKuYDA0EPUgvTwbLHhXu3Pa4LSv6+ltci/hoBJKy2mEtiYgDLB4JY+SCXYseFBBP0c7QXK5NPjrplBMWF2/RWla5VTcjmze1aalMdqt9O4eF5n/4O2agyx/PKale/jjGsZGL2NoE9XZ+SyBcagyFZ77ouTs9jKmW5TwsdQQf+P7/IMnKpcrhh/lQxzmOQr9+/jpANsmW88gCDRLIaaIWtDMNgSCfxeHpNQVXpZNUQs7kMz1vuk/tDwJ8U1K6iGNIc/jrk4+/IXABOdNF5y8DhOKL1C40nzj3r4Sr7KUszhX8hUKGnLHAfbnhJOaTSm2osTlb5/sKllI1yHcQJlHByAyFjCcuI+zw40Szg="
  app: djrecommerce
  on:
    repo: thecoders007/DJReCommerce
  run:
   - "python manage.py makemigrations"
   - "python manage.py migrate"
