language: python

python:
  - 3.6.4
env:
  - DJANGO=2.0.2

  install:
  - pip install -r requirements.txt

  script:
  - flake8
  - python3 manage.py test

  notifications:
  slack:
    on_success: always
    on_failure: always
    
